#!/bin/bash
# Mirror CI execution locally for debugging
# Generated by Test Architect (TEA) agent

echo "🔍 Running CI pipeline locally..."

# Function to run a command and exit on failure
run_command() {
  echo "Running: $1"
  if ! eval "$1"; then
    echo "❌ Command failed: $1"
    exit 1
  fi
}

# Lint - Code quality checks
echo "🧪 Stage 1: Lint"
if [ -f "package.json" ] && [ "$(jq -r '.scripts.lint // empty' package.json)" != "" ]; then
  run_command "npm run lint"
else
  echo "No lint script found in package.json, skipping..."
fi

if [ -f "pyproject.toml" ]; then
  echo "Running Python linting..."
  if command -v flake8 &> /dev/null; then
    run_command "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
  else
    echo "flake8 not installed, installing..."
    uv pip install flake8
    run_command "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
  fi
fi

# Tests - Run test suite
echo "🧪 Stage 2: Tests"
if [ -d "tests" ]; then
  run_command "python -m pytest tests/ -v"
else
  echo "No tests directory found"
fi

if [ -f "package.json" ] && [ "$(jq -r '.scripts.test // empty' package.json)" != "" ]; then
  run_command "npm run test"
fi

# Burn-in - Flaky test detection (reduced iterations for local)
echo "🔥 Stage 3: Burn-in (local)"
if [ -d "tests" ]; then
  echo "Running burn-in loop (3 iterations)..."
  SUCCESS_COUNT=0
  TOTAL_RUNS=3
  
  for i in $(seq 1 $TOTAL_RUNS); do
    echo "🔥 Burn-in $i/$TOTAL_RUNS"
    if python -m pytest tests/ --tb=short; then
      ((SUCCESS_COUNT++))
      echo "✅ Iteration $i passed"
    else
      echo "❌ Iteration $i failed"
    fi
  done
  
  echo "Burn-in results: $SUCCESS_COUNT/$TOTAL_RUNS iterations passed"
  
  # If less than 66% pass rate, fail
  if [ $SUCCESS_COUNT -lt 2 ]; then  # Less than 2 out of 3
    echo "❌ Too many failures in burn-in loop"
    exit 1
  else
    echo "✅ Burn-in loop passed"
  fi
fi

echo "✅ Local CI pipeline passed"