#!/bin/bash
# Run only tests for changed files
# Generated by Test Architect (TEA) agent

echo "🔍 Detecting changed files..."

CHANGED_FILES=$(git diff --name-only HEAD~1)

if [ -z "$CHANGED_FILES" ]; then
  echo "No changed files detected, running all tests..."
  if [ -d "tests" ]; then
    python -m pytest tests/ -v
  fi
  exit 0
fi

echo "Changed files detected:"
echo "$CHANGED_FILES"

PYTHON_FILES_CHANGED=$(echo "$CHANGED_FILES" | grep -E '\.(py)$' | wc -l)
JS_FILES_CHANGED=$(echo "$CHANGED_FILES" | grep -E '\.(js|ts|jsx|tsx)$' | wc -l)

RUN_PYTHON_TESTS=false
RUN_JS_TESTS=false

if [ "$PYTHON_FILES_CHANGED" -gt 0 ]; then
  RUN_PYTHON_TESTS=true
  echo "Python files changed, will run Python tests"
fi

if [ "$JS_FILES_CHANGED" -gt 0 ]; then
  RUN_JS_TESTS=true
  echo "JavaScript/TypeScript files changed, will run JS/TS tests"
fi

# Run Python tests if Python files changed
if [ "$RUN_PYTHON_TESTS" = true ] && [ -d "tests" ]; then
  echo "Running Python tests..."
  python -m pytest tests/ -v
  PYTHON_RESULT=$?
else
  PYTHON_RESULT=0
fi

# Run JS/TS tests if JS/TS files changed
if [ "$RUN_JS_TESTS" = true ]; then
  if [ -f "package.json" ] && [ "$(jq -r '.scripts.test // empty' package.json)" != "" ]; then
    echo "Running JavaScript/TypeScript tests..."
    npm run test
    JS_RESULT=$?
  else
    JS_RESULT=0
  fi
fi

# Exit with error if any tests failed
if [ $PYTHON_RESULT -ne 0 ] || [ $JS_RESULT -ne 0 ]; then
  echo "❌ Some tests failed"
  exit 1
else
  echo "✅ All relevant tests passed"
  exit 0
fi